### ISSUE TITLE
Missing assignment operator

### ISSUE THREAD

**Issue by elanorigby** [groovemonkey/digitalocean-terraform#1]
Hi! Thanks for putting this together.
I believe the var block in `templates.tf` needs an assignment operator, like 
```
vars = {}
```
Without the = I got an Unsupported Block Type error. 
The documentation shows an assignment in this context, too. 
https://www.terraform.io/docs/providers/template/d/file.html

Maybe this changed since you did the tutorial ¯\\\_(ツ)\_/¯

Cheers!

**Comment by groovemonkey** [comment]
Sorry that I just noticed this so late. I have a *lot* of github noise from my work org and this got lost in all the notifications! This issue has been fixed via https://github.com/groovemonkey/digitalocean-terraform/pull/4
