### ISSUE TITLE
Error in terraform apply relating to host: attribute

### ISSUE THREAD

**Issue by mantisgb** [groovemonkey/digitalocean-terraform#2]
Terraform error 30s after starting to create haproxy-web:
Error: Incorrect attribute value type: Inappropriate value for attribute "host": string required.

I think this is due to terraform 0.12 updates. I ran the following:
terraform 0.12upgrade

This added the following lines in haproxy-web.tf, web1.tf and web2.tf
`host = self.ipv4_address`

This works as described in the videos.

**Comment by groovemonkey** [comment]
Fixed via https://github.com/groovemonkey/digitalocean-terraform/pull/4 -- thanks to @clarkkozak !
